@url=http://localhost:3001/api
@json=Content-Type: application/json

### 查看所有用户
get {{url}}/users


### 注册
post {{url}}/register
{{json}}

{
    "username": "test22q13",
    "password": "123456"
}


### 登录
post {{url}}/login
{{json}}

{
    "username": "test22q13",
    "password": "123456"
}


### 个人信息
get {{url}}/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmZjNjZjOTllMDkxNzBhMDA1OGJmMmEiLCJpYXQiOjE2MTAzNzg0Mzd9.WFYEMH0dP-TV_60SgbR6o-vJQvVh05bNnMN4uPhbqug
