@url=http://localhost:3001/api
@json=Content-Type: application/json

### 查看所有用户
get {{url}}/users

### 删除所有用户
delete {{url}}/delete


### 注册
post {{url}}/register
{{json}}

{
    "username": "93",
    "password": "123456",
    "nick": "test",
    "QQ": "1285419578",
    "email": "123@qq.com"
}


### 登录
post {{url}}/login
{{json}}

{
    "username": "93",
    "password": "123456"
}


### 个人信息
get {{url}}/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmZkNDcyNTc5NjM1YzBmMDQ0NTZmZTEiLCJpYXQiOjE2MTA0MzQzNjR9.pIrUD_johyMHm-k93VzLUzfP_gKcQaBvPWkENibsiQU


### 列黑名单
get {{url}}/list/all

### 查黑名单
post {{url}}/list
{{json}}

{
    "QQ": "1914644780"
}

### 加黑名单
post {{url}}/list/add
{{json}}

{
    "QQ": "1285419578",
    "name": "玖叁",
    "level": 1,
    "reason": "咕咕咕时间过长"
}

### 清空黑名单
delete {{url}}/list/clear